version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with clang
          command: sh ci/linux.sh clang_build
      - store_artifacts:
          path: build/output/libNFLogger.zip
          destination: libNFLogger.zip
  buildlinuxgcc:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with gcc
          command: sh ci/linux.sh gcc_build
      - store_artifacts:
          path: build/output/libNFLogger.zip
          destination: libNFLogger.zip
  buildmac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build OSX
          command: sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFLogger.zip
          destination: libNFLogger.zip
  buildmacios:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build iOS
          command: BUILD_IOS=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFLogger.zip
          destination: libNFLogger.zip
workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildlinuxgcc
      - buildmac
      - buildmacios
